export const FETCH_DRUG = "FETCH_DRUG";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const FETCH_DRUG_CONFIG = "FETCH_DRUG_CONFIG";
export const FETCH_DATA_CONFIG_SUCCESS = "FETCH_DATA_CONFIG_SUCCESS";
export const FETCH_DATA_CONFIG_FAILURE = "FETCH_DATA_CONFIG_FAILURE";
