export const FETCH_DRUG = "FETCH_DRUG";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const FETCH_DRUG_CONFIG = "FETCH_DRUG_CONFIG";
export const FETCH_DATA_CONFIG_SUCCESS = "FETCH_DATA_CONFIG_SUCCESS";
export const FETCH_DATA_CONFIG_FAILURE = "FETCH_DATA_CONFIG_FAILURE";

export const UPDATE_DRUG_ORDER_SUCCESS = "UPDATE_DRUG_ORDER_SUCCESS";
export const UPDATE_COLUMN_ORDER_SUCCESS = "UPDATE_COLUMN_ORDER_SUCCESS";
export const UPDATE_CONFIG_SUCCESS = 'UPDATE_CONFIG_SUCCESS';
